### ISSUE TITLE
trench gun reload

### ISSUE THREAD

**Issue by DerpedCrusader** [thyjukki/NZP-Reboot#12]
If you spam click trench gun, it interupts the animation and starts over

**Comment by hellomotolegacy** [comment]
This is present in the PSP version of the game as well, so it might've been added on purpose? I don't want to "fix" this when it was purposeful.

**Comment by thyjukki** [comment]
Most likely a error

**Comment by MotoLegacy** [comment]
Year and a half late but:

As of the current build, the only "interrupted animation" is during reloading. You're able to cancel the reload animation before it finishes loading **every** round. This is normal. Closing.
