### ISSUE TITLE
Transparent texture

### ISSUE THREAD

**Issue by DerpedCrusader** [thyjukki/NZP-Reboot#18]
add transparent texture stufffsss (I don't know the technical teerrrmmssss)

**Comment by Naievil** [comment]
If you are referring to spr32 with better alpha support then there isn't much we can do. However, if you're talking about HL rendermodes then this has been there from the beginning. 

If you're talking about transparency in mdl's then I'm not sure where to help, both spr32 and mdl texture rendering is taken care of by the engine. Which one were you talking about?
