### ISSUE TITLE
PSP Performance

### ISSUE THREAD

**Issue by TheMrIron2** [thyjukki/NZP-Reboot#30]
For PSP, I've noticed that the game doesn't appear to be running as well as it could be. So here's a few tips for you in case you want to look into improving performance, in order of priority:

- Moving sound code (or other misc. code?) to the Media Engine CPU. This secondary CPU is literally the same CPU as the main processor, and even has its own 2MB of local RAM.. you could save CPU calls and memory by moving audio to this among other things
- Look into optimizing the maps a bit more; use `skip`, `hintskip` and whatever else JACK allows you to use, eg. using `func_wall` (or equivalent) for objects that are visible but do not have any major lighting impact on the scene to cut down vis time and BSP size. (Barrels outside the playable area?)
- Disabling unnecessary effects (eg. water ripple; is water even a _thing_ in NZP?)

I also have one or two other tips pertaining to performance:
- Memory/bandwidth for textures isn't an issue and you could safely use some higher resolution alternatives with no performance hit; current textures are mostly 64x64 and while some look fine, some (sandbags?) could look nicer if given a bit more detail or resolution
- I haven't experimented with this myself, but perhaps a mode for the PSP's 480i/p TV mode would be worth looking into; you could potentially get away with 640x448, like a PS2 game. (Maybe 512x448 if memory is short?) Additionally, this would allow Vita/PSTV users running the PSP game via backwards compatibility to enjoy some better image quality, so not just PSP users with a set of TV cables would benefit.

**Comment by MotoLegacy** [comment]
Closing as suggestion regarding sound processing has been implemented and performance is not hindered by the GPU in most cases - feel free to create a new issue specific to requesting TV mode implementation
