### ISSUE TITLE
Game crashes when opening and shuts off my psp

### ISSUE THREAD

**Issue by OlkerZ** [thyjukki/NZP-Reboot#44]

**Comment by MotoLegacy** [comment]
Please provide more detail, as this does not help in the slightest, and make sure you follow the README. Thanks!

**Comment by OlkerZ** [comment]
I am using a psp e1000 street I don't know if these will help 
[nzp_log.txt](https://github.com/thyjukki/NZP-Reboot/files/4516795/nzp_log.txt)
[condebug.log](https://github.com/thyjukki/NZP-Reboot/files/4516797/condebug.log)

**Comment by MotoLegacy** [comment]
These do nothing for me, do you not get any sort of warning on screen after launching the game?

**Comment by OlkerZ** [comment]
I found out what the problem was the game started working when I disabled the "tweakdisplay" plugin im really sorry for wasting your time
