### ISSUE TITLE
Upload Progs.dat

### ISSUE THREAD

**Issue by robertbrann18** [thyjukki/NZP-Reboot#46]
Could you upload the progs.dat for PSP? I was able to download all the files directly on my PS Vita, but I don’t have the updated progs.dat to play. It doesn’t allow older versions for obvious reason.

**Comment by MotoLegacy** [comment]
From what I recall, we used to push progs.dat to the repository but it led to a lot of dumb conflictions, so it became a nusaunce. We'll start posting releases shortly, but until then hop into the Discord and ask, we'll distribute them there if you cannot compile on your own
