### ISSUE TITLE
Issues when extracting the .zip file

### ISSUE THREAD

**Issue by Hurikejn** [thyjukki/NZP-Reboot#54]
Good day, every time I would like to extract the .zip file, it says that I have to replace files while extracting, should I replace everything while extracing? (Please, keep in mind that I did not extract it before and I have tried moving it into other folders as well) 

I appreciate your answering.

**Comment by BCDeshiG** [comment]
Yh hit replace when you're extracting the files. I'm not sure why it does this though to be honest.

**Comment by Hurikejn** [comment]
Oh, I see. It works totally fine now, many thanks for your help.
